#!/bin/bash
# Release: Optimized for Speed

echo "---------------------Compiling /bin/faststatics---------------------"
rm bin/faststatics
cd src
g++ -std=c++0x -I"../" -O2 -Wall -c -fmessage-length=0 faststatics.cpp 
g++ -L"../lib" -o ../bin/faststatics faststatics.o -lSuperficieN -lBaseN
rm faststatics.o
cd ..
